package com.ankat.model;

/**
 * Autogenerated by Avro *
 * DO NOT EDIT DIRECTLY
 */

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class CamMessage extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
    private static final long serialVersionUID = -7446032267228706671L;
    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CamMessage\",\"namespace\":\"com.nordea.gfm.ssca.model\",\"fields\":[{\"name\":\"entityId\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]},{\"name\":\"entityType\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]},{\"name\":\"clientId\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]},{\"name\":\"caseStatusCode\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]},{\"name\":\"caseSubStatusCode\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]},{\"name\":\"fraudType\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]},{\"name\":\"caseActionCode\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]},{\"name\":\"actionApplied\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]},{\"name\":\"updatedTs\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]},{\"name\":\"caseActionId\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]},{\"name\":\"cardIdCardVerNoInstId\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]}]}");

    public static org.apache.avro.Schema getClassSchema() {
        return SCHEMA$;
    }

    private static SpecificData MODEL$ = new SpecificData();
    private static final BinaryMessageEncoder<CamMessage> ENCODER = new BinaryMessageEncoder<CamMessage>(MODEL$, SCHEMA$);
    private static final BinaryMessageDecoder<CamMessage> DECODER = new BinaryMessageDecoder<CamMessage>(MODEL$, SCHEMA$);

    /**
     * Return the BinaryMessageDecoder instance used by this class.
     */
    public static BinaryMessageDecoder<CamMessage> getDecoder() {
        return DECODER;
    }

    /**
     * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
     *
     * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
     */
    public static BinaryMessageDecoder<CamMessage> createDecoder(SchemaStore resolver) {
        return new BinaryMessageDecoder<CamMessage>(MODEL$, SCHEMA$, resolver);
    }

    /**
     * Serializes this CamMessage to a ByteBuffer.
     */
    public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
        return ENCODER.encode(this);
    }

    /**
     * Deserializes a CamMessage from a ByteBuffer.
     */
    public static CamMessage fromByteBuffer(java.nio.ByteBuffer b) throws java.io.IOException {
        return DECODER.decode(b);
    }

    @Deprecated
    public String entityId;
    @Deprecated
    public String entityType;
    @Deprecated
    public String clientId;
    @Deprecated
    public String caseStatusCode;
    @Deprecated
    public String caseSubStatusCode;
    @Deprecated
    public String fraudType;
    @Deprecated
    public String caseActionCode;
    @Deprecated
    public String actionApplied;
    @Deprecated
    public String updatedTs;
    @Deprecated
    public String caseActionId;
    @Deprecated
    public String cardIdCardVerNoInstId;

    /**
     * Default constructor.  Note that this does not initialize fields
     * to their default values from the schema.  If that is desired then
     * one should use <code>newBuilder().
     */
    public CamMessage() {
    }

    /**
     * All-args constructor.
     * @param entityId The new value for entityId
     * @param entityType The new value for entityType
     * @param clientId The new value for clientId
     * @param caseStatusCode The new value for caseStatusCode
     * @param caseSubStatusCode The new value for caseSubStatusCode
     * @param fraudType The new value for fraudType
     * @param caseActionCode The new value for caseActionCode
     * @param actionApplied The new value for actionApplied
     * @param updatedTs The new value for updatedTs
     * @param caseActionId The new value for caseActionId
     * @param cardIdCardVerNoInstId The new value for cardIdCardVerNoInstId
     */
    public CamMessage(String entityId, String entityType, String clientId, String caseStatusCode, String caseSubStatusCode, String fraudType, String caseActionCode, String actionApplied, String updatedTs, String caseActionId, String cardIdCardVerNoInstId) {
        this.entityId = entityId;
        this.entityType = entityType;
        this.clientId = clientId;
        this.caseStatusCode = caseStatusCode;
        this.caseSubStatusCode = caseSubStatusCode;
        this.fraudType = fraudType;
        this.caseActionCode = caseActionCode;
        this.actionApplied = actionApplied;
        this.updatedTs = updatedTs;
        this.caseActionId = caseActionId;
        this.cardIdCardVerNoInstId = cardIdCardVerNoInstId;
    }

    public org.apache.avro.Schema getSchema() {
        return SCHEMA$;
    }    // Used by DatumWriter.  Applications should not call.

    public Object get(int field$) {
        switch (field$) {
            case 0:
                return entityId;
            case 1:
                return entityType;
            case 2:
                return clientId;
            case 3:
                return caseStatusCode;
            case 4:
                return caseSubStatusCode;
            case 5:
                return fraudType;
            case 6:
                return caseActionCode;
            case 7:
                return actionApplied;
            case 8:
                return updatedTs;
            case 9:
                return caseActionId;
            case 10:
                return cardIdCardVerNoInstId;
            default:
                throw new org.apache.avro.AvroRuntimeException("Bad index");
        }
    }

    // Used by DatumReader.  Applications should not call.
    @SuppressWarnings(value = "unchecked")
    public void put(int field$, Object value$) {
        switch (field$) {
            case 0:
                entityId = (String) value$;
                break;
            case 1:
                entityType = (String) value$;
                break;
            case 2:
                clientId = (String) value$;
                break;
            case 3:
                caseStatusCode = (String) value$;
                break;
            case 4:
                caseSubStatusCode = (String) value$;
                break;
            case 5:
                fraudType = (String) value$;
                break;
            case 6:
                caseActionCode = (String) value$;
                break;
            case 7:
                actionApplied = (String) value$;
                break;
            case 8:
                updatedTs = (String) value$;
                break;
            case 9:
                caseActionId = (String) value$;
                break;
            case 10:
                cardIdCardVerNoInstId = (String) value$;
                break;
            default:
                throw new org.apache.avro.AvroRuntimeException("Bad index");
        }
    }

    /**
     * Gets the value of the 'entityId' field.
     *
     * @return The value of the 'entityId' field.
     */
    public String getEntityId() {
        return entityId;
    }

    /**
     * Sets the value of the 'entityId' field.
     *
     * @param value the value to set.
     */
    public void setEntityId(String value) {
        this.entityId = value;
    }

    /**
     * Gets the value of the 'entityType' field.
     *
     * @return The value of the 'entityType' field.
     */
    public String getEntityType() {
        return entityType;
    }

    /**
     * Sets the value of the 'entityType' field.
     *
     * @param value the value to set.
     */
    public void setEntityType(String value) {
        this.entityType = value;
    }

    /**
     * Gets the value of the 'clientId' field.
     *
     * @return The value of the 'clientId' field.
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * Sets the value of the 'clientId' field.
     *
     * @param value the value to set.
     */
    public void setClientId(String value) {
        this.clientId = value;
    }

    /**
     * Gets the value of the 'caseStatusCode' field.
     *
     * @return The value of the 'caseStatusCode' field.
     */
    public String getCaseStatusCode() {
        return caseStatusCode;
    }

    /**
     * Sets the value of the 'caseStatusCode' field.
     *
     * @param value the value to set.
     */
    public void setCaseStatusCode(String value) {
        this.caseStatusCode = value;
    }

    /**
     * Gets the value of the 'caseSubStatusCode' field.
     *
     * @return The value of the 'caseSubStatusCode' field.
     */
    public String getCaseSubStatusCode() {
        return caseSubStatusCode;
    }

    /**
     * Sets the value of the 'caseSubStatusCode' field.
     *
     * @param value the value to set.
     */
    public void setCaseSubStatusCode(String value) {
        this.caseSubStatusCode = value;
    }

    /**
     * Gets the value of the 'fraudType' field.
     *
     * @return The value of the 'fraudType' field.
     */
    public String getFraudType() {
        return fraudType;
    }

    /**
     * Sets the value of the 'fraudType' field.
     *
     * @param value the value to set.
     */
    public void setFraudType(String value) {
        this.fraudType = value;
    }

    /**
     * Gets the value of the 'caseActionCode' field.
     *
     * @return The value of the 'caseActionCode' field.
     */
    public String getCaseActionCode() {
        return caseActionCode;
    }

    /**
     * Sets the value of the 'caseActionCode' field.
     *
     * @param value the value to set.
     */
    public void setCaseActionCode(String value) {
        this.caseActionCode = value;
    }

    /**
     * Gets the value of the 'actionApplied' field.
     *
     * @return The value of the 'actionApplied' field.
     */
    public String getActionApplied() {
        return actionApplied;
    }

    /**
     * Sets the value of the 'actionApplied' field.
     *
     * @param value the value to set.
     */
    public void setActionApplied(String value) {
        this.actionApplied = value;
    }

    /**
     * Gets the value of the 'updatedTs' field.
     *
     * @return The value of the 'updatedTs' field.
     */
    public String getUpdatedTs() {
        return updatedTs;
    }

    /**
     * Sets the value of the 'updatedTs' field.
     *
     * @param value the value to set.
     */
    public void setUpdatedTs(String value) {
        this.updatedTs = value;
    }

    /**
     * Gets the value of the 'caseActionId' field.
     *
     * @return The value of the 'caseActionId' field.
     */
    public String getCaseActionId() {
        return caseActionId;
    }

    /**
     * Sets the value of the 'caseActionId' field.
     *
     * @param value the value to set.
     */
    public void setCaseActionId(String value) {
        this.caseActionId = value;
    }

    /**
     * Gets the value of the 'cardIdCardVerNoInstId' field.
     *
     * @return The value of the 'cardIdCardVerNoInstId' field.
     */
    public String getCardIdCardVerNoInstId() {
        return cardIdCardVerNoInstId;
    }

    /**
     * Sets the value of the 'cardIdCardVerNoInstId' field.
     *
     * @param value the value to set.
     */
    public void setCardIdCardVerNoInstId(String value) {
        this.cardIdCardVerNoInstId = value;
    }

    /**
     * Creates a new CamMessage RecordBuilder.
     *
     * @return A new CamMessage RecordBuilder
     */
    public static Builder newBuilder() {
        return new Builder();
    }

    /**
     * Creates a new CamMessage RecordBuilder by copying an existing Builder.
     *
     * @param other The existing builder to copy.
     * @return A new CamMessage RecordBuilder
     */
    public static Builder newBuilder(Builder other) {
        return new Builder(other);
    }

    /**
     * Creates a new CamMessage RecordBuilder by copying an existing CamMessage instance.
     *
     * @param other The existing instance to copy.
     * @return A new CamMessage RecordBuilder
     */
    public static Builder newBuilder(CamMessage other) {
        return new Builder(other);
    }

    /**
     * RecordBuilder for CamMessage instances.
     */
    public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CamMessage> implements org.apache.avro.data.RecordBuilder<CamMessage> {
        private String entityId;
        private String entityType;
        private String clientId;
        private String caseStatusCode;
        private String caseSubStatusCode;
        private String fraudType;
        private String caseActionCode;
        private String actionApplied;
        private String updatedTs;
        private String caseActionId;
        private String cardIdCardVerNoInstId;

        /**
         * Creates a new Builder
         */
        private Builder() {
            super(SCHEMA$);
        }

        /**
         * Creates a Builder by copying an existing Builder.
         *
         * @param other The existing Builder to copy.
         */
        private Builder(Builder other) {
            super(other);
            if (isValidValue(fields()[0], other.entityId)) {
                this.entityId = data().deepCopy(fields()[0].schema(), other.entityId);
                fieldSetFlags()[0] = true;
            }
            if (isValidValue(fields()[1], other.entityType)) {
                this.entityType = data().deepCopy(fields()[1].schema(), other.entityType);
                fieldSetFlags()[1] = true;
            }
            if (isValidValue(fields()[2], other.clientId)) {
                this.clientId = data().deepCopy(fields()[2].schema(), other.clientId);
                fieldSetFlags()[2] = true;
            }
            if (isValidValue(fields()[3], other.caseStatusCode)) {
                this.caseStatusCode = data().deepCopy(fields()[3].schema(), other.caseStatusCode);
                fieldSetFlags()[3] = true;
            }
            if (isValidValue(fields()[4], other.caseSubStatusCode)) {
                this.caseSubStatusCode = data().deepCopy(fields()[4].schema(), other.caseSubStatusCode);
                fieldSetFlags()[4] = true;
            }
            if (isValidValue(fields()[5], other.fraudType)) {
                this.fraudType = data().deepCopy(fields()[5].schema(), other.fraudType);
                fieldSetFlags()[5] = true;
            }
            if (isValidValue(fields()[6], other.caseActionCode)) {
                this.caseActionCode = data().deepCopy(fields()[6].schema(), other.caseActionCode);
                fieldSetFlags()[6] = true;
            }
            if (isValidValue(fields()[7], other.actionApplied)) {
                this.actionApplied = data().deepCopy(fields()[7].schema(), other.actionApplied);
                fieldSetFlags()[7] = true;
            }
            if (isValidValue(fields()[8], other.updatedTs)) {
                this.updatedTs = data().deepCopy(fields()[8].schema(), other.updatedTs);
                fieldSetFlags()[8] = true;
            }
            if (isValidValue(fields()[9], other.caseActionId)) {
                this.caseActionId = data().deepCopy(fields()[9].schema(), other.caseActionId);
                fieldSetFlags()[9] = true;
            }
            if (isValidValue(fields()[10], other.cardIdCardVerNoInstId)) {
                this.cardIdCardVerNoInstId = data().deepCopy(fields()[10].schema(), other.cardIdCardVerNoInstId);
                fieldSetFlags()[10] = true;
            }
        }

        /**
         * Creates a Builder by copying an existing CamMessage instance
         *
         * @param other The existing instance to copy.
         */
        private Builder(CamMessage other) {
            super(SCHEMA$);
            if (isValidValue(fields()[0], other.entityId)) {
                this.entityId = data().deepCopy(fields()[0].schema(), other.entityId);
                fieldSetFlags()[0] = true;
            }
            if (isValidValue(fields()[1], other.entityType)) {
                this.entityType = data().deepCopy(fields()[1].schema(), other.entityType);
                fieldSetFlags()[1] = true;
            }
            if (isValidValue(fields()[2], other.clientId)) {
                this.clientId = data().deepCopy(fields()[2].schema(), other.clientId);
                fieldSetFlags()[2] = true;
            }
            if (isValidValue(fields()[3], other.caseStatusCode)) {
                this.caseStatusCode = data().deepCopy(fields()[3].schema(), other.caseStatusCode);
                fieldSetFlags()[3] = true;
            }
            if (isValidValue(fields()[4], other.caseSubStatusCode)) {
                this.caseSubStatusCode = data().deepCopy(fields()[4].schema(), other.caseSubStatusCode);
                fieldSetFlags()[4] = true;
            }
            if (isValidValue(fields()[5], other.fraudType)) {
                this.fraudType = data().deepCopy(fields()[5].schema(), other.fraudType);
                fieldSetFlags()[5] = true;
            }
            if (isValidValue(fields()[6], other.caseActionCode)) {
                this.caseActionCode = data().deepCopy(fields()[6].schema(), other.caseActionCode);
                fieldSetFlags()[6] = true;
            }
            if (isValidValue(fields()[7], other.actionApplied)) {
                this.actionApplied = data().deepCopy(fields()[7].schema(), other.actionApplied);
                fieldSetFlags()[7] = true;
            }
            if (isValidValue(fields()[8], other.updatedTs)) {
                this.updatedTs = data().deepCopy(fields()[8].schema(), other.updatedTs);
                fieldSetFlags()[8] = true;
            }
            if (isValidValue(fields()[9], other.caseActionId)) {
                this.caseActionId = data().deepCopy(fields()[9].schema(), other.caseActionId);
                fieldSetFlags()[9] = true;
            }
            if (isValidValue(fields()[10], other.cardIdCardVerNoInstId)) {
                this.cardIdCardVerNoInstId = data().deepCopy(fields()[10].schema(), other.cardIdCardVerNoInstId);
                fieldSetFlags()[10] = true;
            }
        }

        /**
         * Gets the value of the 'entityId' field.
         *
         * @return The value.
         */
        public String getEntityId() {
            return entityId;
        }

        /**
         * Sets the value of the 'entityId' field.
         *
         * @param value The value of 'entityId'.
         * @return This builder.
         */
        public Builder setEntityId(String value) {
            validate(fields()[0], value);
            this.entityId = value;
            fieldSetFlags()[0] = true;
            return this;
        }

        /**
         * Checks whether the 'entityId' field has been set.
         *
         * @return True if the 'entityId' field has been set, false otherwise.
         */
        public boolean hasEntityId() {
            return fieldSetFlags()[0];
        }

        /**
         * Clears the value of the 'entityId' field.
         *
         * @return This builder.
         */
        public Builder clearEntityId() {
            entityId = null;
            fieldSetFlags()[0] = false;
            return this;
        }

        /**
         * Gets the value of the 'entityType' field.
         *
         * @return The value.
         */
        public String getEntityType() {
            return entityType;
        }

        /**
         * Sets the value of the 'entityType' field.
         *
         * @param value The value of 'entityType'.
         * @return This builder.
         */
        public Builder setEntityType(String value) {
            validate(fields()[1], value);
            this.entityType = value;
            fieldSetFlags()[1] = true;
            return this;
        }

        /**
         * Checks whether the 'entityType' field has been set.
         *
         * @return True if the 'entityType' field has been set, false otherwise.
         */
        public boolean hasEntityType() {
            return fieldSetFlags()[1];
        }

        /**
         * Clears the value of the 'entityType' field.
         *
         * @return This builder.
         */
        public Builder clearEntityType() {
            entityType = null;
            fieldSetFlags()[1] = false;
            return this;
        }

        /**
         * Gets the value of the 'clientId' field.
         *
         * @return The value.
         */
        public String getClientId() {
            return clientId;
        }

        /**
         * Sets the value of the 'clientId' field.
         *
         * @param value The value of 'clientId'.
         * @return This builder.
         */
        public Builder setClientId(String value) {
            validate(fields()[2], value);
            this.clientId = value;
            fieldSetFlags()[2] = true;
            return this;
        }

        /**
         * Checks whether the 'clientId' field has been set.
         *
         * @return True if the 'clientId' field has been set, false otherwise.
         */
        public boolean hasClientId() {
            return fieldSetFlags()[2];
        }

        /**
         * Clears the value of the 'clientId' field.
         *
         * @return This builder.
         */
        public Builder clearClientId() {
            clientId = null;
            fieldSetFlags()[2] = false;
            return this;
        }

        /**
         * Gets the value of the 'caseStatusCode' field.
         *
         * @return The value.
         */
        public String getCaseStatusCode() {
            return caseStatusCode;
        }

        /**
         * Sets the value of the 'caseStatusCode' field.
         *
         * @param value The value of 'caseStatusCode'.
         * @return This builder.
         */
        public Builder setCaseStatusCode(String value) {
            validate(fields()[3], value);
            this.caseStatusCode = value;
            fieldSetFlags()[3] = true;
            return this;
        }

        /**
         * Checks whether the 'caseStatusCode' field has been set.
         *
         * @return True if the 'caseStatusCode' field has been set, false otherwise.
         */
        public boolean hasCaseStatusCode() {
            return fieldSetFlags()[3];
        }

        /**
         * Clears the value of the 'caseStatusCode' field.
         *
         * @return This builder.
         */
        public Builder clearCaseStatusCode() {
            caseStatusCode = null;
            fieldSetFlags()[3] = false;
            return this;
        }

        /**
         * Gets the value of the 'caseSubStatusCode' field.
         *
         * @return The value.
         */
        public String getCaseSubStatusCode() {
            return caseSubStatusCode;
        }

        /**
         * Sets the value of the 'caseSubStatusCode' field.
         *
         * @param value The value of 'caseSubStatusCode'.
         * @return This builder.
         */
        public Builder setCaseSubStatusCode(String value) {
            validate(fields()[4], value);
            this.caseSubStatusCode = value;
            fieldSetFlags()[4] = true;
            return this;
        }

        /**
         * Checks whether the 'caseSubStatusCode' field has been set.
         *
         * @return True if the 'caseSubStatusCode' field has been set, false otherwise.
         */
        public boolean hasCaseSubStatusCode() {
            return fieldSetFlags()[4];
        }

        /**
         * Clears the value of the 'caseSubStatusCode' field.
         *
         * @return This builder.
         */
        public Builder clearCaseSubStatusCode() {
            caseSubStatusCode = null;
            fieldSetFlags()[4] = false;
            return this;
        }

        /**
         * Gets the value of the 'fraudType' field.
         *
         * @return The value.
         */
        public String getFraudType() {
            return fraudType;
        }

        /**
         * Sets the value of the 'fraudType' field.
         *
         * @param value The value of 'fraudType'.
         * @return This builder.
         */
        public Builder setFraudType(String value) {
            validate(fields()[5], value);
            this.fraudType = value;
            fieldSetFlags()[5] = true;
            return this;
        }

        /**
         * Checks whether the 'fraudType' field has been set.
         *
         * @return True if the 'fraudType' field has been set, false otherwise.
         */
        public boolean hasFraudType() {
            return fieldSetFlags()[5];
        }

        /**
         * Clears the value of the 'fraudType' field.
         *
         * @return This builder.
         */
        public Builder clearFraudType() {
            fraudType = null;
            fieldSetFlags()[5] = false;
            return this;
        }

        /**
         * Gets the value of the 'caseActionCode' field.
         * * @return The value.
         */
        public String getCaseActionCode() {
            return caseActionCode;
        }

        /**
         * Sets the value of the 'caseActionCode' field.
         *
         * @param value The value of 'caseActionCode'.
         * @return This builder.
         */
        public Builder setCaseActionCode(String value) {
            validate(fields()[6], value);
            this.caseActionCode = value;
            fieldSetFlags()[6] = true;
            return this;
        }

        /**
         * Checks whether the 'caseActionCode' field has been set.
         *
         * @return True if the 'caseActionCode' field has been set, false otherwise.
         */
        public boolean hasCaseActionCode() {
            return fieldSetFlags()[6];
        }

        /**
         * Clears the value of the 'caseActionCode' field.
         *
         * @return This builder.
         */
        public Builder clearCaseActionCode() {
            caseActionCode = null;
            fieldSetFlags()[6] = false;
            return this;
        }

        /**
         * Gets the value of the 'actionApplied' field.
         *
         * @return The value.
         */
        public String getActionApplied() {
            return actionApplied;
        }

        /**
         * Sets the value of the 'actionApplied' field.
         *
         * @param value The value of 'actionApplied'.
         * @return This builder.
         */
        public Builder setActionApplied(String value) {
            validate(fields()[7], value);
            this.actionApplied = value;
            fieldSetFlags()[7] = true;
            return this;
        }

        /**
         * Checks whether the 'actionApplied' field has been set.
         *
         * @return True if the 'actionApplied' field has been set, false otherwise.
         */
        public boolean hasActionApplied() {
            return fieldSetFlags()[7];
        }

        /**
         * Clears the value of the 'actionApplied' field.
         *
         * @return This builder.
         */
        public Builder clearActionApplied() {
            actionApplied = null;
            fieldSetFlags()[7] = false;
            return this;
        }

        /**
         * Gets the value of the 'updatedTs' field.
         *
         * @return The value.
         */
        public String getUpdatedTs() {
            return updatedTs;
        }

        /**
         * Sets the value of the 'updatedTs' field.
         *
         * @param value The value of 'updatedTs'.
         * @return This builder.
         */
        public Builder setUpdatedTs(String value) {
            validate(fields()[8], value);
            this.updatedTs = value;
            fieldSetFlags()[8] = true;
            return this;
        }

        /**
         * Checks whether the 'updatedTs' field has been set.
         *
         * @return True if the 'updatedTs' field has been set, false otherwise.
         */
        public boolean hasUpdatedTs() {
            return fieldSetFlags()[8];
        }

        /**
         * Clears the value of the 'updatedTs' field.
         *
         * @return This builder.
         */
        public Builder clearUpdatedTs() {
            updatedTs = null;
            fieldSetFlags()[8] = false;
            return this;
        }

        /**
         * Gets the value of the 'caseActionId' field.
         *
         * @return The value.
         */
        public String getCaseActionId() {
            return caseActionId;
        }

        /**
         * Sets the value of the 'caseActionId' field.
         *
         * @param value The value of 'caseActionId'.
         * @return This builder.
         */
        public Builder setCaseActionId(String value) {
            validate(fields()[9], value);
            this.caseActionId = value;
            fieldSetFlags()[9] = true;
            return this;
        }

        /**
         * Checks whether the 'caseActionId' field has been set.
         *
         * @return True if the 'caseActionId' field has been set, false otherwise.
         */
        public boolean hasCaseActionId() {
            return fieldSetFlags()[9];
        }

        /**
         * Clears the value of the 'caseActionId' field.
         *
         * @return This builder.
         */
        public Builder clearCaseActionId() {
            caseActionId = null;
            fieldSetFlags()[9] = false;
            return this;
        }

        /**
         * Gets the value of the 'cardIdCardVerNoInstId' field.
         *
         * @return The value.
         */
        public String getCardIdCardVerNoInstId() {
            return cardIdCardVerNoInstId;
        }

        /**
         * Sets the value of the 'cardIdCardVerNoInstId' field.
         *
         * @param value The value of 'cardIdCardVerNoInstId'.
         * @return This builder.
         */
        public Builder setCardIdCardVerNoInstId(String value) {
            validate(fields()[10], value);
            this.cardIdCardVerNoInstId = value;
            fieldSetFlags()[10] = true;
            return this;
        }

        /**
         * Checks whether the 'cardIdCardVerNoInstId' field has been set.
         *
         * @return True if the 'cardIdCardVerNoInstId' field has been set, false otherwise.
         */
        public boolean hasCardIdCardVerNoInstId() {
            return fieldSetFlags()[10];
        }

        /**
         * Clears the value of the 'cardIdCardVerNoInstId' field.
         *
         * @return This builder.
         */
        public Builder clearCardIdCardVerNoInstId() {
            cardIdCardVerNoInstId = null;
            fieldSetFlags()[10] = false;
            return this;
        }

        @Override
        @SuppressWarnings("unchecked")
        public CamMessage build() {
            try {
                CamMessage record = new CamMessage();
                record.entityId = fieldSetFlags()[0] ? this.entityId : (String) defaultValue(fields()[0]);
                record.entityType = fieldSetFlags()[1] ? this.entityType : (String) defaultValue(fields()[1]);
                record.clientId = fieldSetFlags()[2] ? this.clientId : (String) defaultValue(fields()[2]);
                record.caseStatusCode = fieldSetFlags()[3] ? this.caseStatusCode : (String) defaultValue(fields()[3]);
                record.caseSubStatusCode = fieldSetFlags()[4] ? this.caseSubStatusCode : (String) defaultValue(fields()[4]);
                record.fraudType = fieldSetFlags()[5] ? this.fraudType : (String) defaultValue(fields()[5]);
                record.caseActionCode = fieldSetFlags()[6] ? this.caseActionCode : (String) defaultValue(fields()[6]);
                record.actionApplied = fieldSetFlags()[7] ? this.actionApplied : (String) defaultValue(fields()[7]);
                record.updatedTs = fieldSetFlags()[8] ? this.updatedTs : (String) defaultValue(fields()[8]);
                record.caseActionId = fieldSetFlags()[9] ? this.caseActionId : (String) defaultValue(fields()[9]);
                record.cardIdCardVerNoInstId = fieldSetFlags()[10] ? this.cardIdCardVerNoInstId : (String) defaultValue(fields()[10]);
                return record;
            } catch (Exception e) {
                throw new org.apache.avro.AvroRuntimeException(e);
            }
        }
    }

    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumWriter<CamMessage> WRITER$ = (org.apache.avro.io.DatumWriter<CamMessage>) MODEL$.createDatumWriter(SCHEMA$);

    @Override
    public void writeExternal(java.io.ObjectOutput out) throws java.io.IOException {
        WRITER$.write(this, SpecificData.getEncoder(out));
    }

    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumReader<CamMessage> READER$ = (org.apache.avro.io.DatumReader<CamMessage>) MODEL$.createDatumReader(SCHEMA$);

    @Override
    public void readExternal(java.io.ObjectInput in) throws java.io.IOException {
        READER$.read(this, SpecificData.getDecoder(in));
    }
}